
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf65f090ew6554178do.mysql.rds.aliyuncs.com/diyi_cr_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: diyi_cr_20200714
    password: A#9JJu6Hv8

# 阿里云OSS云存储配置
aliyun:
  oss:
    domain: https://diyi-cr.oss-cn-shanghai.aliyuncs.com
    endPoint: http://oss-cn-shanghai.aliyuncs.com
    bucketName: diyi-cr
    accessKeyId: LTAI4GDMovvBWMpWk2VTDBpq
    accessKeySecret: yO6t0rEOSxTr4tPSZ4w1ZxMy1n0Hmf
    prefix: upload
