
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}

# 阿里云OSS云存储配置
aliyun:
  oss:
    domain: https://diyi-cr.oss-cn-shanghai.aliyuncs.com
    endPoint: http://oss-cn-shanghai.aliyuncs.com
    bucketName: diyi-cr
    accessKeyId: LTAI4GDMovvBWMpWk2VTDBpq
    accessKeySecret: yO6t0rEOSxTr4tPSZ4w1ZxMy1n0Hmf
    prefix: upload