#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  # redis 配置
  redis:
    ##redis 单机环境配置
    host: 127.0.0.1
    port: 6379
    password: 652f72da3960ce4449
    database: 0
    ssl: false
